services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: subscriptions_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Opcional: para acessar o BD diretamente do host

volumes:
  db_data: